from config import Base

from models.abm_requests import ABMRequest
from models.areas_mails import AreaMail
from models.audit_receipts import AuditReceipt
from models.change_history import ChangeHistory
from models.clients import Client
from models.credentials import Credential
from models.day_types import DayType
from models.department_heads import DepartmentHead
from models.departments import Department
from models.document_areas import DocumentArea
from models.document_roles import DocumentRole
from models.document_versions import DocumentVersion
from models.documents import Document
from models.employee_areas import EmployeeArea
from models.employee_roles import EmployeeRole
from models.employees import Employee
from models.equipment import Equipment
from models.files import File
from models.internal_news import InternalNews
from models.lunch_schedules import LunchSchedule
from models.mails import Mail
from models.news_areas import NewsArea
from models.news_roles import NewsRole
from models.notifications import Notification
from models.permissions import Permission
from models.requested_days import RequestedDay
from models.roles import Role
from models.room_reservations import RoomReservation
from models.rooms import Room
from models.salary_receipts import SalaryReceipt
from models.survey_answers import SurveyAnswer
from models.survey_areas import SurveyArea
from models.survey_questions import SurveyQuestion
from models.survey_responses import SurveyResponse
from models.survey_roles import SurveyRole
from models.surveys import Survey
from models.system_tickets import SystemTicket
from models.ticket_categories import TicketCategory
from models.ticket_subcategories import TicketSubcategory
from models.ticket_updates import TicketUpdate
from models.trained_employees import TrainedEmployee
from models.training_materials import TrainingMaterial
from models.trainings import Training
from models.user_logins import UserLogin